### ISSUE TITLE
Налаштувати SSL сертифікати

### ISSUE THREAD

**Issue by olesmartyniuk** [olesmartyniuk/russian-sites-status-api#42]
Зараз сайти які працюють по HTTPS не зможуть використовувати наш API, так як він працює по HTTP. Політика безпеки браузера не дасть можливість виконати запит HTTPS => HTTP.

Нам необхідно знайти сертифікат в першу чергу для API домену: api.mordor-sites-status.info і в другу чергу для сайту: mordor-sites-status.info

Необхідно:
1. Купити сертфиікат
2. Підключити його для нашого серверу (Heroku + Docker + ASP.NET + Kestrel)
3. Зконтактувати з @ajukraine в Telegram, він колись пропонував допомогу з сертифікатом
4. Якщо все добре і не дорого, налаштувати сертифікат для сайту (Heroku + Docker + Nginx + Static Files)

**Comment by BasilKosovan** [comment]
https://stackoverflow.com/questions/50049200/how-to-setup-domain-with-ssl-in-heroku
