### ISSUE TITLE
Пошук сайту по URL

### ISSUE THREAD

**Issue by olesmartyniuk** [olesmartyniuk/russian-sites-status-api#5]
Необхідно реалізувати новий API метод, що здійснює пошук сайту по URL.
`GET api/sites/search?url=TEXT`

Вимоги:
1. Кількість сайтів всього< 1000
2. Мінімальна кількість симоволів для пошуку - 3
3. Пошук по масці `*TEXT*` в адресі сайту
4. Відкидати протокол та www
5. Швидкість швидкість виконання запиту < 300ms
6. Повертати загальну інформацію про сайт (результат аналогічний до методу sites). Приклад
`{"id":"6300089","name":"https://ya.ru/","testType":"HTTP","websiteUrl":"https://ya.ru/","status":"up","uptime":"100 %"}`

**Comment by BasilKosovan** [comment]
Привіт, хочу взяти на себе цю задачу. 
Hey, I would like to pick up this issue.
